services:
  - type: web
    name: f1-ai-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python app/rag/ingest.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.12
